"""SAGE Core — Problem Classifier.

Classifies optimization problems into tiers (instant, fast, background)
based on model dimensions and problem type. Drives routing decisions
in sage-solver-mcp.

No filesystem access. No network calls. No side effects (except optional 50ms probe).
"""

from __future__ import annotations

import logging
import time
from typing import Literal

from pydantic import BaseModel

from sage_solver_core.models import (
    LPModel,
    MIPModel,
    PortfolioModel,
    SchedulingModel,
    SolverInput,
)
from sage_solver_core.builder import build_from_lp, build_from_mip

logger = logging.getLogger("sage.classifier")

AnyModel = LPModel | MIPModel | PortfolioModel | SchedulingModel


class ClassificationResult(BaseModel):
    """Result of classifying an optimization problem into a complexity tier.

    Attributes:
        tier: Complexity tier — ``instant``, ``fast``, or ``background``.
        reasoning: Human-readable explanation of why this tier was chosen.
        estimated_seconds: Rough estimated solve time in seconds.
        signals: Diagnostic dict with n_vars, n_binary, n_constraints, etc.
    """

    tier: Literal["instant", "fast", "background"]
    reasoning: str
    estimated_seconds: float
    signals: dict


def _count_dimensions(model: AnyModel) -> tuple[int, int, int, str]:
    """Count variables, binary/integer vars, constraints, and detect problem type.

    Returns:
        (n_vars, n_binary, n_constraints, problem_type)
    """
    if isinstance(model, LPModel):
        n_vars = len(model.variables)
        n_binary = 0
        n_constraints = len(model.constraints)
        problem_type = "lp"
    elif isinstance(model, MIPModel):
        n_vars = len(model.variables)
        n_binary = sum(
            1 for v in model.variables if v.var_type in ("binary", "integer")
        )
        n_constraints = len(model.constraints)
        problem_type = "mip"
    elif isinstance(model, PortfolioModel):
        n_vars = len(model.assets)
        n_binary = 0
        n_constraints = 0  # constraints are implicit in PortfolioConstraints
        problem_type = "portfolio"
    elif isinstance(model, SchedulingModel):
        n_vars = len(model.workers) * len(model.shifts) * model.planning_horizon_days
        n_binary = n_vars  # all binary
        n_constraints = 0  # constraints are generated by builder
        problem_type = "scheduling"
    else:
        # Defensive fallback — should never happen with type hints
        n_vars = 0
        n_binary = 0
        n_constraints = 0
        problem_type = "unknown"

    return n_vars, n_binary, n_constraints, problem_type


def _get_time_limit(model: AnyModel) -> float | None:
    """Extract time_limit_seconds if the model has one."""
    return getattr(model, "time_limit_seconds", None)


def _run_probe(model: MIPModel) -> float | None:
    """Run a quick LP relaxation probe on an ambiguous MIP.

    Builds a SolverInput from the MIP, relaxes all integer/binary vars
    to continuous, and solves with a 50ms time limit.

    Returns:
        Solve time in milliseconds, or None if the probe failed.
    """
    try:
        solver_input = build_from_mip(model)
        # Relax all variables to continuous for LP relaxation
        relaxed = solver_input.model_copy(
            update={
                "variable_types": ["continuous"] * solver_input.num_variables,
                "time_limit_seconds": 0.05,  # 50ms
            }
        )
        from sage_solver_core.solver import solve

        t0 = time.perf_counter()
        solve(relaxed)
        elapsed_ms = (time.perf_counter() - t0) * 1000.0
        return elapsed_ms
    except Exception:
        logger.debug("LP relaxation probe failed; defaulting to fast", exc_info=True)
        return None


def classify(model: AnyModel) -> ClassificationResult:
    """Classify an optimization problem into a complexity tier.

    The tier determines how the MCP/cloud layer should route the problem:

    - **instant**: Expected to solve in under 1 second. Synchronous.
    - **fast**: Expected to solve in 1-60 seconds. Synchronous with progress.
    - **background**: May take minutes+. Asynchronous / queued.

    Classification rules (first match wins):

    1. n_binary > 500 OR n_vars > 50,000 -> background
    2. n_binary > 100 OR explicit time_limit > 60s -> fast
    3. Pure LP -> instant
    4. QP / Portfolio -> instant
    5. Small MIP (n_binary <= 100, n_vars <= 1000) -> instant
    6. Scheduling with n_binary > 500 -> background
    7. Scheduling -> fast (default)

    For ambiguous MIPs (n_binary ~50-100), an optional 50ms LP relaxation
    probe refines the estimate.

    Args:
        model: Any SAGE optimization model.

    Returns:
        ClassificationResult with tier, reasoning, estimated_seconds, and signals.
    """
    n_vars, n_binary, n_constraints, problem_type = _count_dimensions(model)
    time_limit = _get_time_limit(model)
    has_time_limit = time_limit is not None

    signals: dict = {
        "n_vars": n_vars,
        "n_binary": n_binary,
        "n_constraints": n_constraints,
        "problem_type": problem_type,
        "has_time_limit": has_time_limit,
        "time_limit": time_limit,
    }

    # Rule 1: Very large problems -> background
    if n_binary > 500 or n_vars > 50_000:
        reasoning = (
            f"Large problem: {n_vars} variables, {n_binary} binary/integer. "
            "Expected to require significant solve time."
        )
        return ClassificationResult(
            tier="background",
            reasoning=reasoning,
            estimated_seconds=300.0,
            signals=signals,
        )

    # Rule 2: Medium binary count or long explicit time limit -> fast
    if n_binary > 100 or (has_time_limit and time_limit is not None and time_limit > 60):
        reasoning_parts = []
        if n_binary > 100:
            reasoning_parts.append(f"{n_binary} binary/integer variables")
        if has_time_limit and time_limit is not None and time_limit > 60:
            reasoning_parts.append(f"explicit time limit of {time_limit}s > 60s")
        reasoning = f"Moderate complexity: {'; '.join(reasoning_parts)}."
        return ClassificationResult(
            tier="fast",
            reasoning=reasoning,
            estimated_seconds=30.0,
            signals=signals,
        )

    # Rule 3: Pure LP -> instant
    if problem_type == "lp":
        reasoning = (
            f"Pure LP with {n_vars} variables, {n_constraints} constraints. "
            "No integer variables."
        )
        return ClassificationResult(
            tier="instant",
            reasoning=reasoning,
            estimated_seconds=0.1,
            signals=signals,
        )

    # Rule 4: Portfolio / QP -> instant
    if problem_type == "portfolio":
        reasoning = (
            f"Portfolio (QP) with {n_vars} assets. "
            "Quadratic programs solve quickly for typical portfolio sizes."
        )
        return ClassificationResult(
            tier="instant",
            reasoning=reasoning,
            estimated_seconds=0.5,
            signals=signals,
        )

    # Rule 5: Small MIP -> instant (with optional probe for ambiguous cases)
    if problem_type == "mip" and n_binary <= 100 and n_vars <= 1000:
        # Ambiguous zone: n_binary between 50 and 100 — run probe
        if 50 <= n_binary <= 100 and isinstance(model, MIPModel):
            probe_ms = _run_probe(model)
            if probe_ms is not None:
                signals["probe_time_ms"] = round(probe_ms, 2)
                if probe_ms < 10:
                    reasoning = (
                        f"Small MIP with {n_binary} binary vars. "
                        f"LP relaxation probe solved in {probe_ms:.1f}ms — instant."
                    )
                    return ClassificationResult(
                        tier="instant",
                        reasoning=reasoning,
                        estimated_seconds=0.5,
                        signals=signals,
                    )
                else:
                    reasoning = (
                        f"MIP with {n_binary} binary vars. "
                        f"LP relaxation probe took {probe_ms:.1f}ms — fast."
                    )
                    return ClassificationResult(
                        tier="fast",
                        reasoning=reasoning,
                        estimated_seconds=5.0,
                        signals=signals,
                    )
            else:
                # Probe failed, default to fast for ambiguous range
                reasoning = (
                    f"MIP with {n_binary} binary vars in ambiguous range. "
                    "Probe failed; defaulting to fast."
                )
                return ClassificationResult(
                    tier="fast",
                    reasoning=reasoning,
                    estimated_seconds=5.0,
                    signals=signals,
                )

        reasoning = (
            f"Small MIP with {n_binary} binary/integer vars, {n_vars} total. "
            "Expected to solve quickly."
        )
        return ClassificationResult(
            tier="instant",
            reasoning=reasoning,
            estimated_seconds=0.5,
            signals=signals,
        )

    # Rule 6: Large scheduling -> background
    if problem_type == "scheduling" and n_binary > 500:
        reasoning = (
            f"Large scheduling problem: {n_binary} binary variables "
            f"({n_vars} total). May require significant solve time."
        )
        return ClassificationResult(
            tier="background",
            reasoning=reasoning,
            estimated_seconds=300.0,
            signals=signals,
        )

    # Rule 7: Scheduling -> fast (default)
    if problem_type == "scheduling":
        reasoning = (
            f"Scheduling problem with {n_binary} binary variables. "
            "Scheduling MIPs typically need moderate solve time."
        )
        return ClassificationResult(
            tier="fast",
            reasoning=reasoning,
            estimated_seconds=15.0,
            signals=signals,
        )

    # Fallback: unknown or uncovered cases -> fast
    reasoning = (
        f"Unclassified problem type '{problem_type}' with {n_vars} vars, "
        f"{n_binary} binary. Defaulting to fast."
    )
    return ClassificationResult(
        tier="fast",
        reasoning=reasoning,
        estimated_seconds=10.0,
        signals=signals,
    )
