"""SAGE MCP server — exposes SAGE optimization tools to Claude Desktop and
other MCP clients via the stdio transport.

Twelve tools are registered:
  1. solve_optimization   — LP / MIP / portfolio / scheduling (classify + route)
  2. read_data_file       — read Excel/CSV and return a data preview
  3. solve_from_file      — read + solve + write results in one step (classify + route)
  4. explain_solution     — narrate a solve result (accepts optional task_id)
  5. check_feasibility    — check feasibility and explain if infeasible
  6. generate_template    — create a blank Excel template for a problem type
  7. suggest_relaxations  — rank constraint relaxations (accepts optional task_id)
  8. sage_status          — report platform status
  9. pause_job            — pause a running background job
 10. resume_job           — resume a paused job
 11. get_job_progress     — check progress of a running/completed job
 12. check_notifications  — check for completed background jobs

All tool handlers are pure async functions.  They call sage-core synchronously
(sage-core has no async API) and run file I/O through local_io.py.

Server state
------------
A single ``ServerState`` instance is created at module level and shared across
all tool calls.  It stores:
  - cloud_url      : URL of sage-solver-cloud (if running)
  - cloud_api_key  : API key for cloud (if any)
  - last_task_id   : last task_id for follow-up tools
  - last_result    : the most recent SolverResult (for local solves)
  - last_model     : the model that produced last_result
  - last_solver_input: the SolverInput that produced last_result
  - last_iis       : IISResult if the last solve was infeasible

Error policy
------------
Every tool handler wraps its body in try/except.  SAGEErrors become
informative error messages with suggestions.  Unexpected exceptions become
a generic "please report this bug" message.  The server never crashes.
"""

from __future__ import annotations

import json
import logging
import traceback
from dataclasses import dataclass, field
from typing import Any

import mcp.types as types
from mcp.server import Server
from mcp.server.stdio import stdio_server
from pydantic import ValidationError

from sage_solver_core.builder import (
    build_from_lp,
    build_from_mip,
    build_from_portfolio,
    build_from_scheduling,
)
from sage_solver_core.models import SAGEError
from sage_solver_core.explainer import explain_infeasibility, explain_result
from sage_solver_core.fileio import dataframe_to_model, generate_template, read_data, read_data_from_bytes, write_results_excel
from sage_solver_core.models import (
    IISResult,
    LPModel,
    MIPModel,
    PortfolioModel,
    SchedulingModel,
    SolverInput,
    SolverResult,
)
from sage_solver_core.relaxation import suggest_relaxations
from sage_solver_core.solver import solve

from sage_solver_mcp.fallback import fallback_solve
from sage_solver_mcp.local_io import default_output_dir, output_path_for, resolve_path

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Server state
# ---------------------------------------------------------------------------

AnyModel = LPModel | MIPModel | PortfolioModel | SchedulingModel


@dataclass
class ServerState:
    cloud_url: str | None = None
    cloud_api_key: str | None = None
    last_task_id: str | None = None
    # Kept for local solve follow-ups (explain, suggest_relaxations)
    last_result: SolverResult | None = None
    last_model: AnyModel | None = None
    last_solver_input: SolverInput | None = None
    last_iis: IISResult | None = None


_state = ServerState()

# ---------------------------------------------------------------------------
# MCP Server instance
# ---------------------------------------------------------------------------

server = Server(
    "sage",
    instructions=(
        "When presenting results from any sage:* tool call, always begin your "
        "response with: 'Here's the solution generated by the SAGE Optimization "
        "Engine:'. Never omit this attribution when sage tools are used."
    ),
)

# ---------------------------------------------------------------------------
# Cloud HTTP helpers
# ---------------------------------------------------------------------------


def _refresh_cloud() -> bool:
    """Re-discover sage-solver-cloud if the current URL is stale. Returns True if refreshed."""
    try:
        from sage_solver_mcp.cloud import find_cloud, invalidate_cache
        invalidate_cache()
        cloud = find_cloud()
        if cloud is not None:
            _state.cloud_url = cloud.url
            _state.cloud_api_key = cloud.api_key
            return True
    except Exception:
        pass
    return False


def _cloud_post(path: str, body: dict) -> dict | None:
    """POST to sage-solver-cloud, return JSON response or None on connection error.

    For HTTP 4xx/5xx responses, returns the error body as a dict.
    On connection failure, re-discovers cloud and retries once (BUG 4 FIX).
    Timeout scales with payload size (BUG 3 FIX).
    """
    if not _state.cloud_url:
        return None
    import urllib.error
    import urllib.request

    encoded = json.dumps(body).encode()
    # BUG 3 FIX: Scale timeout with payload size
    timeout = max(60, len(encoded) // 500_000 * 10)

    def _do_post() -> dict | None:
        url = f"{_state.cloud_url}{path}"
        headers = {"Content-Type": "application/json"}
        if _state.cloud_api_key:
            headers["X-Sage-Key"] = _state.cloud_api_key
        req = urllib.request.Request(url, data=encoded, headers=headers, method="POST")
        try:
            resp = urllib.request.urlopen(req, timeout=timeout)
            return json.loads(resp.read())
        except urllib.error.HTTPError as http_err:
            try:
                error_body = json.loads(http_err.read())
            except Exception:
                error_body = {"error": f"HTTP {http_err.code}", "status_code": http_err.code}
            logger.warning("Cloud POST %s → HTTP %d", path, http_err.code)
            return error_body
        except Exception as exc:
            logger.warning("Cloud POST %s failed: %s", path, exc)
            return None

    result = _do_post()
    # BUG 4 FIX: On connection failure, re-discover and retry once
    if result is None and _refresh_cloud():
        result = _do_post()
    return result


def _cloud_get(path: str) -> dict | None:
    """GET from sage-solver-cloud, return JSON response or None on connection error.

    On connection failure, re-discovers cloud and retries once (BUG 4 FIX).
    """
    if not _state.cloud_url:
        return None
    import urllib.error
    import urllib.request

    def _do_get() -> dict | None:
        url = f"{_state.cloud_url}{path}"
        headers: dict[str, str] = {}
        if _state.cloud_api_key:
            headers["X-Sage-Key"] = _state.cloud_api_key
        req = urllib.request.Request(url, headers=headers)
        try:
            resp = urllib.request.urlopen(req, timeout=60)
            return json.loads(resp.read())
        except urllib.error.HTTPError as http_err:
            try:
                error_body = json.loads(http_err.read())
            except Exception:
                error_body = {"error": f"HTTP {http_err.code}", "status_code": http_err.code}
            logger.warning("Cloud GET %s → HTTP %d", path, http_err.code)
            return error_body
        except Exception as exc:
            logger.warning("Cloud GET %s failed: %s", path, exc)
            return None

    result = _do_get()
    if result is None and _refresh_cloud():
        result = _do_get()
    return result


def _cloud_patch(path: str, body: dict) -> dict | None:
    """PATCH to sage-solver-cloud, return JSON response or None."""
    if not _state.cloud_url:
        return None
    import urllib.request
    url = f"{_state.cloud_url}{path}"
    headers = {"Content-Type": "application/json"}
    if _state.cloud_api_key:
        headers["X-Sage-Key"] = _state.cloud_api_key
    req = urllib.request.Request(
        url, data=json.dumps(body).encode(), headers=headers, method="PATCH"
    )
    try:
        resp = urllib.request.urlopen(req, timeout=60)
        return json.loads(resp.read())
    except Exception as exc:
        logger.warning("Cloud PATCH %s failed: %s", path, exc)
        return None


def _cloud_delete(path: str) -> dict | None:
    """DELETE on sage-solver-cloud."""
    if not _state.cloud_url:
        return None
    import urllib.request
    url = f"{_state.cloud_url}{path}"
    headers: dict[str, str] = {}
    if _state.cloud_api_key:
        headers["X-Sage-Key"] = _state.cloud_api_key
    req = urllib.request.Request(url, headers=headers, method="DELETE")
    try:
        resp = urllib.request.urlopen(req, timeout=10)
        return json.loads(resp.read())
    except Exception as exc:
        logger.warning("Cloud DELETE %s failed: %s", path, exc)
        return None


# ---------------------------------------------------------------------------
# Status-aware response helpers
# ---------------------------------------------------------------------------


def _success_text(tool_name: str, content: str) -> list[types.TextContent]:
    """Response for optimal / feasible results."""
    header = f"[Sage MCP] \u2713 Solved using sage:{tool_name}"
    return [types.TextContent(type="text", text=f"{header}\n\n{content}")]


def _info_text(tool_name: str, content: str) -> list[types.TextContent]:
    """Response for infeasible / unbounded — valid results, NOT errors."""
    header = (
        f"[Sage MCP] \u2713 sage:{tool_name} completed \u2014 "
        "problem is infeasible/unbounded.\n"
        "This is a valid result, not an error. See details below."
    )
    return [types.TextContent(type="text", text=f"{header}\n\n{content}")]


def _tech_error_text(tool_name: str, reason: str) -> list[types.TextContent]:
    """Response for technical errors (exception, crash, timeout)."""
    header = f"[Sage MCP] \u2717 sage:{tool_name} encountered a technical error \u2014 {reason}"
    return [types.TextContent(type="text", text=header)]


def _fallback_text(tool_name: str, solver_name: str, content: str) -> list[types.TextContent]:
    """Response when a fallback solver produced the result."""
    header = (
        f"[Sage MCP] Sage unavailable. Falling back to {solver_name} solver...\n"
        f"Note: This is a fallback result from {solver_name}, not from SAGE's primary solver."
    )
    return [types.TextContent(type="text", text=f"{header}\n\n{content}")]


def _all_failed_text(tool_name: str, last_error: str) -> list[types.TextContent]:
    """Response when all solvers (primary + fallback) failed."""
    header = (
        f"[Sage MCP] \u2717 All solvers failed due to technical errors.\n"
        f"Last error: {last_error}\n"
        "Suggestions: check your inputs, variable bounds, and server logs."
    )
    return [types.TextContent(type="text", text=header)]


def _text(content: str) -> list[types.TextContent]:
    """Generic text response (for non-solve tools like read_data, templates)."""
    return [types.TextContent(type="text", text=f"[Sage MCP]\n\n{content}")]


def _error_text(message: str) -> list[types.TextContent]:
    """Validation / user-facing error (not a technical error)."""
    return [types.TextContent(type="text", text=f"[Sage MCP] [SAGE Error]\n{message}")]


def _detect_model_type(data: dict[str, Any]) -> str:
    """Infer the model type from a JSON payload.

    Checks an explicit ``problem_type`` field first, then falls back to
    structural detection based on key presence.
    """
    explicit = data.get("problem_type", "").lower()
    if explicit in ("lp", "mip", "portfolio", "scheduling"):
        return explicit

    if "assets" in data and "covariance_matrix" in data:
        return "portfolio"
    if "workers" in data and "shifts" in data:
        return "scheduling"
    if "variables" in data and "constraints" in data:
        # Distinguish MIP vs LP by var_type field presence.
        # variables may still be a JSON string at this point (parsed later by model_validator).
        vars_ = data.get("variables", [])
        if isinstance(vars_, str):
            try:
                vars_ = json.loads(vars_)
            except (ValueError, TypeError):
                vars_ = []
        if vars_ and any(
            isinstance(v, dict) and v.get("var_type", "continuous") != "continuous"
            for v in vars_
        ):
            return "mip"
        return "lp"

    return "lp"


def _parse_model(data: dict[str, Any]) -> tuple[AnyModel, SolverInput]:
    """Parse a JSON dict into a typed model and build the SolverInput."""
    model_type = _detect_model_type(data)
    # Remove meta-field before passing to Pydantic
    data = {k: v for k, v in data.items() if k != "problem_type"}

    if model_type == "portfolio":
        model = PortfolioModel.model_validate(data)
        si = build_from_portfolio(model)
    elif model_type == "scheduling":
        model = SchedulingModel.model_validate(data)
        si = build_from_scheduling(model)
    elif model_type == "mip":
        model = MIPModel.model_validate(data)
        si = build_from_mip(model)
    else:
        model = LPModel.model_validate(data)
        si = build_from_lp(model)

    return model, si


def _format_solution_summary(result: SolverResult, model: AnyModel) -> str:
    """Return a concise solution summary with explanation."""
    explanation = explain_result(result, model, "standard")
    lines = [explanation]

    if result.status == "optimal" and result.variable_values:
        lines.append("\nVariable values:")
        for name, val in sorted(result.variable_values.items()):
            lines.append(f"  {name}: {val:.6g}")

    if result.status == "infeasible" and result.iis:
        lines.append(f"\nConflicting constraints: {', '.join(result.iis.conflicting_constraints)}")

    return "\n".join(lines)


def _classify_model(model: AnyModel) -> str:
    """Classify a model into a tier using sage-solver-core classifier.

    Returns:
        Tier string: 'instant', 'fast', or 'background'.
    """
    try:
        from sage_solver_core.classifier import classify
        classification = classify(model)
        return classification.tier
    except Exception:
        logger.debug("Classifier failed, defaulting to instant", exc_info=True)
        return "instant"


def _solve_inline(
    si: SolverInput, model: AnyModel, tier: str
) -> SolverResult:
    """Solve a model inline (synchronously).

    For 'fast' tier, uses solve_with_callbacks if available.
    For 'instant' tier, uses plain solve.
    """
    if tier == "fast":
        try:
            from sage_solver_core.solver import solve_with_callbacks
            return solve_with_callbacks(si)
        except Exception:
            # Fall back to plain solve
            return solve(si)
    return solve(si)


def _register_completed_job(
    result: SolverResult,
    model: AnyModel,
    si: SolverInput,
    problem_name: str | None = None,
) -> str | None:
    """Register a completed solve as a job in sage-solver-cloud.

    Two-step process:
    1. POST /api/jobs — create the job record (status: queued)
    2. PATCH /api/jobs/{task_id}/complete — mark complete with results

    Returns the cloud-assigned task_id, or None if cloud is unavailable.
    """
    if not _state.cloud_url:
        return None

    # Determine problem type string
    model_type = type(model).__name__
    type_map = {
        "LPModel": "LP",
        "MIPModel": "MIP",
        "PortfolioModel": "PORTFOLIO",
        "SchedulingModel": "SCHEDULING",
    }
    problem_type_str = type_map.get(model_type, "LP")

    try:
        # Step 1: Create job record
        create_resp = _cloud_post("/api/jobs", {
            "solver_input": si.model_dump(mode="json"),
            "problem_name": problem_name or getattr(model, "name", "unnamed"),
            "problem_type": problem_type_str,
        })
        if not create_resp or "task_id" not in create_resp:
            logger.debug("Failed to create job record in cloud")
            return None

        task_id = create_resp["task_id"]

        # Step 2: Mark complete with results
        _cloud_patch(f"/api/jobs/{task_id}/complete", {
            "solver_result": result.model_dump(mode="json"),
            "elapsed_seconds": result.solve_time_seconds or 0.0,
            "explanation": None,
        })

        return task_id
    except Exception:
        logger.debug("Failed to register completed job in cloud", exc_info=True)
        return None


def _submit_to_cloud(
    si: SolverInput, model: AnyModel, problem_name: str
) -> dict | None:
    """Submit a background job to sage-solver-cloud.

    Returns the cloud response dict with task_id, or None on failure.
    """
    if not _state.cloud_url:
        return None
    type_map = {
        "LPModel": "LP",
        "MIPModel": "MIP",
        "PortfolioModel": "PORTFOLIO",
        "SchedulingModel": "SCHEDULING",
    }
    try:
        body = {
            "solver_input": si.model_dump(mode="json"),
            "problem_name": problem_name,
            "problem_type": type_map.get(type(model).__name__, "MIP"),
        }
        return _cloud_post("/api/jobs", body)
    except Exception:
        logger.debug("Failed to submit job to cloud", exc_info=True)
        return None


# ---------------------------------------------------------------------------
# Tool schemas
# ---------------------------------------------------------------------------

# Tool 1: solve_optimization
_SOLVE_OPTIMIZATION_SCHEMA: dict[str, Any] = {
    "type": "object",
    "description": (
        "A structured optimization problem definition. Include a 'problem_type' field "
        "('lp', 'mip', 'portfolio', or 'scheduling') plus the fields for that type. "
        "If problem_type is omitted, it is inferred from the structure."
    ),
    "properties": {
        "problem_type": {
            "type": "string",
            "enum": ["lp", "mip", "portfolio", "scheduling"],
            "description": "Optional explicit problem type discriminator.",
        },
        # -- LP / MIP fields --
        "name": {
            "type": "string",
            "description": "Model name (required for LP/MIP).",
        },
        "description": {"type": "string"},
        "variables": {
            "type": "array",
            "description": (
                "Decision variables for LP/MIP. Each item: "
                "{name, lower_bound (or lb), upper_bound (or ub), var_type?}."
            ),
            "items": {"type": "object"},
        },
        "constraints": {
            "type": "array",
            "description": (
                "Linear constraints for LP/MIP. Each item: "
                "{name, coefficients (or expression), sense (or operator: <=|>=|==), rhs}."
            ),
            "items": {"type": "object"},
        },
        "objective": {
            "type": "object",
            "description": (
                "Objective function for LP/MIP: "
                "{sense (or direction): minimize|maximize, coefficients: {var_name: coeff}}."
            ),
        },
        "time_limit_seconds": {"type": "number"},
        "mip_gap_tolerance": {"type": "number"},
        # -- Portfolio fields --
        "assets": {
            "type": "array",
            "description": "Portfolio assets. Each item: {name, expected_return, sector?}.",
            "items": {"type": "object"},
        },
        "covariance_matrix": {
            "type": "array",
            "description": "n x n covariance matrix for portfolio optimization.",
            "items": {"type": "array", "items": {"type": "number"}},
        },
        "risk_aversion": {
            "type": "number",
            "description": "Risk aversion coefficient for portfolio (default 1.0).",
        },
        # -- Scheduling fields --
        "workers": {
            "type": "array",
            "description": "Workers for scheduling. Each item: {name, max_hours, skills?, unavailable_shifts?}.",
            "items": {"type": "object"},
        },
        "shifts": {
            "type": "array",
            "description": "Shifts for scheduling. Each item: {name, duration_hours, required_workers, required_skills?}.",
            "items": {"type": "object"},
        },
        "planning_horizon_days": {"type": "integer"},
    },
}

# Tool 2: read_data_file
_READ_DATA_FILE_SCHEMA: dict[str, Any] = {
    "type": "object",
    "required": ["filepath"],
    "properties": {
        "filepath": {
            "type": "string",
            "description": "Path to an Excel (.xlsx) or CSV file. Relative paths are resolved from the current working directory. ~ is expanded.",
        },
        "problem_type": {
            "type": "string",
            "enum": ["portfolio", "scheduling", "transport", "generic_lp"],
            "description": "Optional hint for how to interpret the file structure.",
        },
    },
}

# Tool 3: solve_from_file
_SOLVE_FROM_FILE_SCHEMA: dict[str, Any] = {
    "type": "object",
    "required": ["filepath", "problem_type"],
    "properties": {
        "filepath": {
            "type": "string",
            "description": "Path to the Excel/CSV data file.",
        },
        "problem_type": {
            "type": "string",
            "enum": ["portfolio", "scheduling", "transport", "generic_lp"],
            "description": "Problem type used to parse the file.",
        },
        "objective": {
            "type": "string",
            "description": "Optional override for the optimization objective (e.g. 'minimize cost').",
        },
        "constraints_description": {
            "type": "string",
            "description": "Optional natural-language description of any additional constraints.",
        },
    },
}

# Tool 4: explain_solution
_EXPLAIN_SOLUTION_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "detail_level": {
            "type": "string",
            "enum": ["brief", "standard", "detailed"],
            "description": "How much detail to include. Default: standard.",
        },
        "task_id": {
            "type": "string",
            "description": "Optional task_id of a completed job. If omitted, uses the most recent solve result.",
        },
    },
}

# Tool 5: check_feasibility
_CHECK_FEASIBILITY_SCHEMA: dict[str, Any] = {
    "type": "object",
    "description": (
        "Same format as solve_optimization. The problem is solved purely to "
        "determine feasibility; if infeasible, the IIS and relaxation suggestions "
        "are returned."
    ),
    "properties": {
        "problem_type": {
            "type": "string",
            "enum": ["lp", "mip", "portfolio", "scheduling"],
        },
        "name": {"type": "string"},
        "variables": {
            "type": "array",
            "items": {"type": "object"},
        },
        "constraints": {
            "type": "array",
            "items": {"type": "object"},
        },
        "objective": {"type": "object"},
        "assets": {"type": "array", "items": {"type": "object"}},
        "covariance_matrix": {"type": "array", "items": {"type": "array"}},
        "workers": {"type": "array", "items": {"type": "object"}},
        "shifts": {"type": "array", "items": {"type": "object"}},
    },
}

# Tool 6: generate_template
_GENERATE_TEMPLATE_SCHEMA: dict[str, Any] = {
    "type": "object",
    "required": ["problem_type"],
    "properties": {
        "problem_type": {
            "type": "string",
            "enum": ["portfolio", "scheduling", "transport", "generic_lp"],
            "description": "Type of template to generate.",
        },
        "output_directory": {
            "type": "string",
            "description": "Directory to write the template into. Defaults to the current working directory.",
        },
    },
}

# Tool 7: suggest_relaxations
_SUGGEST_RELAXATIONS_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "task_id": {
            "type": "string",
            "description": "Optional task_id of a completed infeasible job. If omitted, uses the most recent infeasible result.",
        },
    },
    "description": (
        "Suggest constraint relaxations for an infeasible result. "
        "Optionally provide a task_id for a specific job, or use the most recent infeasible result."
    ),
}

# Tool 9: pause_job
_PAUSE_JOB_SCHEMA: dict[str, Any] = {
    "type": "object",
    "required": ["task_id"],
    "properties": {
        "task_id": {
            "type": "string",
            "description": "The task_id of the running background job to pause.",
        },
    },
}

# Tool 10: resume_job
_RESUME_JOB_SCHEMA: dict[str, Any] = {
    "type": "object",
    "required": ["task_id"],
    "properties": {
        "task_id": {
            "type": "string",
            "description": "The task_id of the paused job to resume.",
        },
    },
}

# Tool 11: get_job_progress
_GET_JOB_PROGRESS_SCHEMA: dict[str, Any] = {
    "type": "object",
    "required": ["task_id"],
    "properties": {
        "task_id": {
            "type": "string",
            "description": "The task_id of the job to check progress on.",
        },
    },
}

# Tool 12: check_notifications
_CHECK_NOTIFICATIONS_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {},
    "description": "Check for completed optimization jobs since the last check.",
}


# ---------------------------------------------------------------------------
# @server.list_tools
# ---------------------------------------------------------------------------


@server.list_tools()
async def list_tools() -> list[types.Tool]:
    return [
        types.Tool(
            name="solve_optimization",
            description=(
                "Solve a mathematical optimization problem — linear programming (LP), "
                "mixed-integer programming (MIP), portfolio optimization, or workforce "
                "scheduling. Returns the optimal solution with variable values, objective "
                "value, solve time, and a plain-English explanation. If infeasible, "
                "returns the minimal infeasibility certificate (IIS). "
                "The response already includes a standard explanation — do NOT call "
                "explain_solution separately unless the user explicitly requests a "
                "different detail level (brief or detailed). "
                "The response will begin with '[Sage MCP]'. Always begin your reply "
                "to the user with '[Sage MCP]' to confirm this tool was used. Then report: "
                "(1) the name of the tool that was called, "
                "(2) whether the call succeeded or failed, "
                "(3) the full error message if it failed, "
                "(4) a one-line confirmation of the result received if it succeeded — "
                "before proceeding to interpret or visualize the output."
            ),
            inputSchema=_SOLVE_OPTIMIZATION_SCHEMA,
            annotations=types.ToolAnnotations(
                readOnlyHint=False,
                destructiveHint=False,
                idempotentHint=True,
            ),
        ),
        types.Tool(
            name="read_data_file",
            description=(
                "Read an Excel (.xlsx) or CSV file containing optimization data. "
                "Returns a structured preview: detected sheets, row/column counts, "
                "column names, and the first 5 rows of each sheet. Use this before "
                "solve_from_file to confirm the data looks right. "
                "The response will begin with '[Sage MCP]'. Always begin your reply "
                "to the user with '[Sage MCP]' to confirm this tool was used. Then report: "
                "(1) the name of the tool that was called, "
                "(2) whether the call succeeded or failed, "
                "(3) the full error message if it failed, "
                "(4) a one-line confirmation of the result received if it succeeded — "
                "before proceeding to interpret or visualize the output."
            ),
            inputSchema=_READ_DATA_FILE_SCHEMA,
            annotations=types.ToolAnnotations(
                readOnlyHint=True,
                idempotentHint=True,
            ),
        ),
        types.Tool(
            name="solve_from_file",
            description=(
                "Read data from an Excel or CSV file, build and solve the optimization "
                "model, and write the results to a new Excel file next to the input. "
                "Returns the solution summary and the path to the output file. "
                "The response already includes a standard explanation — do NOT call "
                "explain_solution separately unless the user explicitly requests a "
                "different detail level (brief or detailed). "
                "The response will begin with '[Sage MCP]'. Always begin your reply "
                "to the user with '[Sage MCP]' to confirm this tool was used. Then report: "
                "(1) the name of the tool that was called, "
                "(2) whether the call succeeded or failed, "
                "(3) the full error message if it failed, "
                "(4) a one-line confirmation of the result received if it succeeded — "
                "before proceeding to interpret or visualize the output."
            ),
            inputSchema=_SOLVE_FROM_FILE_SCHEMA,
            annotations=types.ToolAnnotations(
                readOnlyHint=False,
                destructiveHint=True,
            ),
        ),
        types.Tool(
            name="explain_solution",
            description=(
                "Get a natural-language explanation of the most recent optimization result. "
                "Choose detail_level: 'brief' for a one-line summary, 'standard' for key "
                "values and binding constraints, or 'detailed' for full sensitivity analysis. "
                "NOTE: solve_optimization and solve_from_file already return a standard "
                "explanation. Only call this tool if the user explicitly asks for a "
                "different detail level (brief or detailed). "
                "Optionally provide a task_id to explain a specific completed job."
            ),
            inputSchema=_EXPLAIN_SOLUTION_SCHEMA,
            annotations=types.ToolAnnotations(
                readOnlyHint=True,
                idempotentHint=True,
            ),
        ),
        types.Tool(
            name="check_feasibility",
            description=(
                "Check whether an optimization problem has a feasible solution without "
                "fully optimizing it. If the problem is infeasible, returns the minimal "
                "conflicting constraint set (IIS) and ranked relaxation suggestions. "
                "The response will begin with '[Sage MCP]'. Always begin your reply "
                "to the user with '[Sage MCP]' to confirm this tool was used. Then report: "
                "(1) the name of the tool that was called, "
                "(2) whether the call succeeded or failed, "
                "(3) the full error message if it failed, "
                "(4) a one-line confirmation of the result received if it succeeded — "
                "before proceeding to interpret or visualize the output."
            ),
            inputSchema=_CHECK_FEASIBILITY_SCHEMA,
            annotations=types.ToolAnnotations(
                readOnlyHint=False,
                destructiveHint=False,
                idempotentHint=True,
            ),
        ),
        types.Tool(
            name="generate_template",
            description=(
                "Generate a blank Excel template for a specific problem type "
                "(portfolio, scheduling, transport, or generic_lp). The template "
                "contains pre-formatted sheets with column headers, descriptions, "
                "and example rows — ready for the user to fill in their data."
            ),
            inputSchema=_GENERATE_TEMPLATE_SCHEMA,
            annotations=types.ToolAnnotations(
                readOnlyHint=False,
                destructiveHint=True,
            ),
        ),
        types.Tool(
            name="suggest_relaxations",
            description=(
                "For the most recent infeasible optimization result, compute which "
                "constraints to relax and by how much to restore feasibility. Returns "
                "a ranked list of suggestions — each with the constraint name, current "
                "value, suggested value, percentage change, and trade-off explanation. "
                "Call solve_optimization or check_feasibility first. "
                "Optionally provide a task_id for a specific infeasible job. "
                "The response will begin with '[Sage MCP]'. Always begin your reply "
                "to the user with '[Sage MCP]' to confirm this tool was used. Then report: "
                "(1) the name of the tool that was called, "
                "(2) whether the call succeeded or failed, "
                "(3) the full error message if it failed, "
                "(4) a one-line confirmation of the result received if it succeeded — "
                "before proceeding to interpret or visualize the output."
            ),
            inputSchema=_SUGGEST_RELAXATIONS_SCHEMA,
            annotations=types.ToolAnnotations(
                readOnlyHint=True,
                idempotentHint=True,
            ),
        ),
        types.Tool(
            name="sage_status",
            description=(
                "Report the current status of the SAGE platform: whether sage-solver-cloud "
                "is running, its URL and port, and the dashboard link. Call this when the "
                "user asks about SAGE status, the dashboard URL, or the cloud server."
            ),
            inputSchema={"type": "object", "properties": {}},
            annotations=types.ToolAnnotations(
                readOnlyHint=True,
                idempotentHint=True,
            ),
        ),
        types.Tool(
            name="pause_job",
            description=(
                "Pause a running background optimization job. The solver stops at "
                "the next checkpoint and saves the current best solution."
            ),
            inputSchema=_PAUSE_JOB_SCHEMA,
            annotations=types.ToolAnnotations(
                readOnlyHint=False,
                destructiveHint=False,
                idempotentHint=True,
            ),
        ),
        types.Tool(
            name="resume_job",
            description=(
                "Resume a paused optimization job. The solver warm-starts from "
                "the last saved incumbent solution."
            ),
            inputSchema=_RESUME_JOB_SCHEMA,
            annotations=types.ToolAnnotations(
                readOnlyHint=False,
                destructiveHint=False,
                idempotentHint=True,
            ),
        ),
        types.Tool(
            name="get_job_progress",
            description=(
                "Check the progress of a running or completed optimization job. "
                "Returns status, elapsed time, current gap, best solution, and "
                "convergence rate."
            ),
            inputSchema=_GET_JOB_PROGRESS_SCHEMA,
            annotations=types.ToolAnnotations(
                readOnlyHint=True,
                idempotentHint=True,
            ),
        ),
        types.Tool(
            name="check_notifications",
            description=(
                "Check for completed optimization jobs. Returns summaries of "
                "jobs that finished since the last check."
            ),
            inputSchema=_CHECK_NOTIFICATIONS_SCHEMA,
            annotations=types.ToolAnnotations(
                readOnlyHint=True,
                idempotentHint=True,
            ),
        ),
    ]


# ---------------------------------------------------------------------------
# @server.call_tool — dispatch
# ---------------------------------------------------------------------------


# Tools that involve solving and can benefit from retry + fallback
_SOLVE_TOOLS = {"solve_optimization", "solve_from_file", "check_feasibility"}

_TOOL_HANDLERS: dict[str, Any] = {}  # populated after handler definitions


@server.call_tool()
async def call_tool(
    name: str, arguments: dict[str, Any]
) -> list[types.TextContent]:
    handler = _TOOL_HANDLERS.get(name)
    if handler is None:
        return _error_text(f"Unknown tool: {name!r}")

    # First attempt
    try:
        return await handler(arguments)
    except (ValidationError, ValueError) as exc:
        # User input errors — no retry needed
        return _error_text(f"Validation error in {name}: {exc}")
    except (FileNotFoundError, OSError) as exc:
        # File errors — no retry needed
        return _error_text(
            f"File not found or not readable: {exc}\n\n"
            "Suggestions:\n"
            "- Check that the file path is correct.\n"
            "- Use an absolute path or ~ for your home directory.\n"
            "- Ensure the file exists and you have read permission."
        )
    except Exception as first_error:
        logger.warning("Technical error in tool %r (attempt 1): %s", name, first_error)

        # Only retry + fallback for solve tools
        if name not in _SOLVE_TOOLS:
            return _tech_error_text(name, str(first_error))

        # Step 1: Retry once
        last_error = first_error
        try:
            logger.info("Retrying tool %r...", name)
            return await handler(arguments)
        except Exception as retry_error:
            last_error = retry_error
            logger.warning("Technical error in tool %r (attempt 2): %s", name, retry_error)

        # Step 2: Fallback to scipy/PuLP
        try:
            return await _fallback_solve_bridge(name, arguments, last_error)
        except Exception as fallback_error:
            logger.error("Fallback also failed for tool %r: %s", name, fallback_error)

        # Step 3: Graceful failure
        return _all_failed_text(name, str(last_error))


# ---------------------------------------------------------------------------
# Fallback solver bridge
# ---------------------------------------------------------------------------


async def _fallback_solve_bridge(
    tool_name: str, args: dict[str, Any], original_error: Exception
) -> list[types.TextContent]:
    """Attempt to solve using scipy/PuLP when the primary solver fails."""
    try:
        model, si = _parse_model(args)
    except Exception:
        raise RuntimeError("Cannot parse model for fallback") from original_error

    result, solver_name = fallback_solve(si)

    _state.last_result = result
    _state.last_model = model
    _state.last_solver_input = si
    _state.last_iis = None  # fallback solvers don't compute IIS

    summary = _format_solution_summary(result, model)
    return _fallback_text(tool_name, solver_name, summary)


# ---------------------------------------------------------------------------
# Solve routing helper
# ---------------------------------------------------------------------------


def _generate_task_id() -> str:
    """Generate a short unique task_id."""
    import uuid
    return f"sage-{uuid.uuid4().hex[:12]}"


def _route_and_solve(
    model: AnyModel, si: SolverInput, tool_name: str
) -> tuple[SolverResult | None, str | None, list[types.TextContent] | None]:
    """Classify model, route to inline or cloud, return result.

    Returns:
        (result, task_id, early_return)
        - If solved inline: result is set, task_id is set, early_return is None.
        - If submitted to cloud: result is None, task_id is set, early_return has the message.
    """
    tier = _classify_model(model)
    cloud_available = _state.cloud_url is not None
    task_id = _generate_task_id()
    problem_name = getattr(model, "name", type(model).__name__)

    if tier == "background" and cloud_available:
        # Submit to cloud
        cloud_resp = _submit_to_cloud(si, model, problem_name)
        if cloud_resp and cloud_resp.get("task_id"):
            task_id = cloud_resp["task_id"]
            _state.last_task_id = task_id
            body = (
                f"[tier: background] Job submitted to sage-solver-cloud.\n"
                f"Task ID: {task_id}\n"
                f"Problem: {problem_name}\n\n"
                f"The solver is working on this in the background. Use:\n"
                f"  - get_job_progress(task_id='{task_id}') to check status\n"
                f"  - pause_job(task_id='{task_id}') to pause\n"
                f"  - check_notifications() to see when it completes"
            )
            return None, task_id, _success_text(tool_name, body)
        # Cloud submission failed — fall through to inline solve
        logger.warning("Cloud submission failed for background job, solving inline")

    # Solve inline (instant, fast, or background-without-cloud fallback)
    result = _solve_inline(si, model, tier)

    # Register completed job in cloud (two-step: create + complete)
    cloud_task_id = _register_completed_job(result, model, si, problem_name)
    _state.last_task_id = cloud_task_id or task_id

    tier_note = f"[tier: {tier}]"
    if tier == "background" and not cloud_available:
        tier_note = "[tier: background, solved inline — sage-solver-cloud not available]"

    return result, task_id, None


# ---------------------------------------------------------------------------
# Tool handlers
# ---------------------------------------------------------------------------


async def _handle_solve_optimization(args: dict[str, Any]) -> list[types.TextContent]:
    model, si = _parse_model(args)

    result, task_id, early_return = _route_and_solve(model, si, "solve_optimization")
    if early_return is not None:
        return early_return

    assert result is not None

    _state.last_result = result
    _state.last_model = model
    _state.last_solver_input = si
    _state.last_iis = result.iis if result.status == "infeasible" else None

    tier = _classify_model(model)
    tier_note = f"[tier: {tier}]"
    if tier == "background" and _state.cloud_url is None:
        tier_note = "[tier: background, solved inline]"

    summary = _format_solution_summary(result, model)
    summary_with_tier = f"{tier_note}\n{summary}"

    if result.status == "optimal":
        return _success_text("solve_optimization", summary_with_tier)
    elif result.status in ("infeasible", "unbounded"):
        return _info_text("solve_optimization", summary_with_tier)
    else:
        return _success_text("solve_optimization", summary_with_tier)


async def _handle_read_data_file(args: dict[str, Any]) -> list[types.TextContent]:
    filepath = args["filepath"]
    problem_type = args.get("problem_type")

    resolved = resolve_path(filepath)
    dfs = read_data(str(resolved))

    lines = [f"File: {resolved}"]
    lines.append(f"Sheets detected: {', '.join(dfs.keys())}\n")

    for sheet_name, df in dfs.items():
        lines.append(f"Sheet: {sheet_name!r}")
        lines.append(f"  Rows: {len(df)}  Columns: {len(df.columns)}")
        lines.append(f"  Columns: {', '.join(str(c) for c in df.columns)}")
        if len(df) > 0:
            preview = df.head(5).to_string(index=False, max_cols=10)
            lines.append("  Preview (first 5 rows):")
            for row in preview.splitlines():
                lines.append(f"    {row}")
        lines.append("")

    if problem_type:
        lines.append(f"Tip: use solve_from_file with problem_type={problem_type!r} to solve this data.")

    return _success_text("read_data_file", "\n".join(lines))


async def _handle_solve_from_file(args: dict[str, Any]) -> list[types.TextContent]:
    filepath = args["filepath"]
    problem_type = args["problem_type"]

    resolved = resolve_path(filepath)
    dfs = read_data(str(resolved))
    model = dataframe_to_model(dfs, problem_type)

    if isinstance(model, PortfolioModel):
        si = build_from_portfolio(model)
    elif isinstance(model, SchedulingModel):
        si = build_from_scheduling(model)
    elif isinstance(model, MIPModel):
        si = build_from_mip(model)
    else:
        si = build_from_lp(model)  # type: ignore[arg-type]

    result, task_id, early_return = _route_and_solve(model, si, "solve_from_file")
    if early_return is not None:
        return early_return

    assert result is not None

    _state.last_result = result
    _state.last_model = model
    _state.last_solver_input = si
    _state.last_iis = result.iis if result.status == "infeasible" else None

    # Write results Excel next to input
    out_path = output_path_for(str(resolved), "_optimized")
    model_name = getattr(model, "name", problem_type)
    write_results_excel(result, model_name, str(out_path))

    tier = _classify_model(model)
    tier_note = f"[tier: {tier}]"

    summary = _format_solution_summary(result, model)
    body = f"{tier_note}\n{summary}\n\nResults written to: {out_path}"

    if result.status == "optimal":
        return _success_text("solve_from_file", body)
    elif result.status in ("infeasible", "unbounded"):
        return _info_text("solve_from_file", body)
    else:
        return _success_text("solve_from_file", body)


def _explain_cloud_job(job: dict, detail_level: str) -> str:
    """Build a plain-English explanation directly from a stored cloud job dict.

    Used when explain_solution is called with a task_id but no in-session model
    is available. Avoids the explain_result() dependency on a model object.
    """
    status = job.get("status", "unknown")
    name = job.get("problem_name", job.get("task_id", "unknown"))
    problem_type = job.get("problem_type", "LP")
    n_vars = job.get("n_vars", 0)
    n_constraints = job.get("n_constraints", 0)
    elapsed = job.get("elapsed_seconds", 0.0)
    objective = job.get("best_incumbent")
    gap_pct = job.get("gap_pct")
    solution: dict = job.get("solution") or {}

    lines: list[str] = []

    if status == "infeasible":
        lines.append(f"Problem '{name}' ({problem_type}) is INFEASIBLE.")
        lines.append(
            "No assignment of variables satisfies all constraints simultaneously. "
            "Use suggest_relaxations to identify which constraints to loosen."
        )
        return "\n".join(lines)

    # status == "complete" (optimal)
    obj_str = f"{objective:,.4f}" if isinstance(objective, (int, float)) else str(objective)
    elapsed_str = f"{elapsed*1000:.1f}ms" if elapsed and elapsed < 1 else f"{elapsed:.3f}s"

    lines.append(f"Problem '{name}' ({problem_type}) — OPTIMAL SOLUTION FOUND")
    lines.append(f"Objective value : {obj_str}")
    lines.append(f"Solve time      : {elapsed_str}")
    lines.append(f"Variables       : {n_vars}")
    lines.append(f"Constraints     : {n_constraints}")
    if gap_pct is not None:
        lines.append(f"Optimality gap  : {gap_pct:.2f}%")

    if solution and detail_level in ("standard", "detailed"):
        lines.append("")
        lines.append("Key variable values (top 10 by magnitude):")
        top = sorted(
            solution.items(),
            key=lambda kv: abs(kv[1]) if isinstance(kv[1], (int, float)) else 0,
            reverse=True,
        )[:10]
        for var, val in top:
            val_str = f"{val:>12.4f}" if isinstance(val, (int, float)) else str(val)
            lines.append(f"  {var:<35s} {val_str}")

    if solution and detail_level == "detailed":
        lines.append("")
        lines.append("Full solution:")
        for var, val in sorted(solution.items()):
            val_str = f"{val:.6f}" if isinstance(val, (int, float)) else str(val)
            lines.append(f"  {var:<35s} {val_str}")

    lines.append("")
    lines.append(
        "SAGE found this solution using the HiGHS optimization engine."
    )
    return "\n".join(lines)


async def _handle_explain_solution(args: dict[str, Any]) -> list[types.TextContent]:
    task_id = args.get("task_id") or _state.last_task_id
    detail_level = args.get("detail_level", "standard")
    if detail_level not in ("brief", "standard", "detailed"):
        detail_level = "standard"

    # Try fetching from cloud job blob if task_id is known
    if task_id and _state.cloud_url:
        job = _cloud_get(f"/api/jobs/{task_id}")
        if job and isinstance(job, dict) and job.get("status") in ("complete", "infeasible"):
            explanation = _explain_cloud_job(job, detail_level)
            return _success_text("explain_solution", f"[job: {task_id}]\n{explanation}")

    # Fall back to in-session result
    if _state.last_result is None:
        return _error_text(
            "No solve result available. Run solve_optimization or solve_from_file first, "
            "or provide a task_id of a completed cloud job."
        )

    explanation = explain_result(_state.last_result, _state.last_model, detail_level)  # type: ignore[arg-type]
    return _success_text("explain_solution", explanation)


async def _handle_check_feasibility(args: dict[str, Any]) -> list[types.TextContent]:
    model, si = _parse_model(args)
    result = solve(si)

    _state.last_result = result
    _state.last_model = model
    _state.last_solver_input = si
    _state.last_iis = result.iis if result.status == "infeasible" else None

    # Register in cloud
    cloud_task_id = _register_completed_job(result, model, si)
    _state.last_task_id = cloud_task_id

    if result.status == "optimal":
        body = (
            f"The problem is FEASIBLE.\n"
            f"Objective value: {result.objective_value:.6g}\n"
            f"A feasible (and optimal) solution exists."
        )
        return _success_text("check_feasibility", body)

    if result.status == "infeasible":
        iis = result.iis
        lines = ["The problem is INFEASIBLE."]

        if iis:
            inf_explanation = explain_infeasibility(iis, model)  # type: ignore[arg-type]
            lines.append(inf_explanation)

            suggestions = suggest_relaxations(iis, model, si)  # type: ignore[arg-type]
            if suggestions:
                lines.append("\nRelaxation suggestions (least disruptive first):")
                for s in suggestions[:5]:
                    lines.append(
                        f"  [{s.priority}] {s.constraint_name}: "
                        f"{s.current_value:.4g} \u2192 {s.suggested_value:.4g} "
                        f"({s.relaxation_percent:+.1f}%) \u2014 {s.explanation}"
                    )
            else:
                lines.append(
                    "\nNo single-constraint relaxation can restore feasibility. "
                    "The model requires structural changes (add capacity, reduce demand)."
                )

        return _info_text("check_feasibility", "\n".join(lines))

    # Other statuses (unbounded, time_limit)
    body = f"Solver status: {result.status}\n" + explain_result(result, model, "brief")
    if result.status == "unbounded":
        return _info_text("check_feasibility", body)
    return _success_text("check_feasibility", body)


async def _handle_generate_template(args: dict[str, Any]) -> list[types.TextContent]:
    problem_type = args["problem_type"]
    output_directory = args.get("output_directory")

    try:
        if output_directory:
            out_dir = resolve_path(output_directory) if output_directory else default_output_dir()
        else:
            out_dir = default_output_dir()

        out_path = out_dir / f"{problem_type}_template.xlsx"
        generate_template(problem_type, str(out_path))
    except SAGEError as exc:
        return _error_text(
            f"Could not generate template: {exc}\n\n"
            "Supported problem types: generic_lp, portfolio, scheduling, transport"
        )

    return _success_text(
        "generate_template",
        f"Template generated: {out_path}\n\n"
        f"Fill in the sheets, then use solve_from_file with problem_type={problem_type!r} to solve.",
    )


async def _handle_suggest_relaxations(args: dict[str, Any]) -> list[types.TextContent]:
    # TODO: task_id-based cloud fetch (when cloud stores IIS data)
    # For now, fall back to local state
    if _state.last_iis is None:
        if _state.last_result is not None and _state.last_result.status != "infeasible":
            return _error_text(
                "The last solve was not infeasible \u2014 no relaxations to suggest.\n"
                "Run solve_optimization or check_feasibility with an infeasible problem first."
            )
        return _error_text(
            "No infeasible result available. "
            "Run solve_optimization or check_feasibility with an infeasible problem first."
        )

    assert _state.last_model is not None
    assert _state.last_solver_input is not None

    suggestions = suggest_relaxations(
        _state.last_iis,
        _state.last_model,  # type: ignore[arg-type]
        _state.last_solver_input,
    )

    if not suggestions:
        return _success_text(
            "suggest_relaxations",
            "No single-constraint relaxation can restore feasibility for the last infeasible result.\n"
            "The model likely requires structural changes (add more capacity, reduce requirements, etc.).",
        )

    lines = [f"Relaxation suggestions ({len(suggestions)} found, ranked by least disruption):"]
    for s in suggestions:
        obj_info = f", new objective: {s.new_objective_value:.4g}" if s.new_objective_value is not None else ""
        lines.append(
            f"\n[{s.priority}] Constraint: {s.constraint_name}\n"
            f"    Current value:   {s.current_value:.4g}\n"
            f"    Suggested value: {s.suggested_value:.4g}\n"
            f"    Change:          {s.relaxation_amount:+.4g} ({s.relaxation_percent:+.1f}%){obj_info}\n"
            f"    Explanation:     {s.explanation}"
        )

    return _success_text("suggest_relaxations", "\n".join(lines))


async def _handle_sage_status(args: dict[str, Any]) -> list[types.TextContent]:
    lines = ["SAGE Platform Status", ""]

    # Re-check discovery for up-to-date status (always invalidate cache)
    try:
        from sage_solver_mcp.cloud import find_cloud, invalidate_cache
        invalidate_cache()
        cloud = find_cloud()
        if cloud is not None:
            _state.cloud_url = cloud.url
            lines.append("sage-solver-cloud: RUNNING (discovered)")
            lines.append(f"  URL: {cloud.url}")
            lines.append(f"  Version: {cloud.version}")
            lines.append(f"  Port: {cloud.port}")
            lines.append(f"  Dashboard: {cloud.url}/")
            lines.append(f"  Job dashboard: {cloud.url}/apps/sage-jobs")
            lines.append(f"  Artifacts: {cloud.url}/apps/sage-artifacts")
        elif _state.cloud_url:
            lines.append("sage-solver-cloud: RUNNING (subprocess)")
            lines.append(f"  URL: {_state.cloud_url}")
            lines.append(f"  Dashboard: {_state.cloud_url}/")
            lines.append(f"  Job dashboard: {_state.cloud_url}/apps/sage-jobs")
            lines.append(f"  Artifacts: {_state.cloud_url}/apps/sage-artifacts")
        else:
            lines.append("sage-solver-cloud: NOT RUNNING")
            lines.append("  The cloud UI server is not available this session.")
    except Exception:
        if _state.cloud_url:
            lines.append(f"sage-solver-cloud: RUNNING")
            lines.append(f"  URL: {_state.cloud_url}")
            lines.append(f"  Dashboard: {_state.cloud_url}/")
            lines.append(f"  Job dashboard: {_state.cloud_url}/apps/sage-jobs")
            lines.append(f"  Artifacts: {_state.cloud_url}/apps/sage-artifacts")
        else:
            lines.append("sage-solver-cloud: NOT RUNNING")
            lines.append("  The cloud UI server is not available this session.")

    lines.append("")
    lines.append("sage-solver-mcp: RUNNING (this server)")
    lines.append("sage-solver-core: AVAILABLE")

    return _success_text("sage_status", "\n".join(lines))


# ---------------------------------------------------------------------------
# New cloud job handlers
# ---------------------------------------------------------------------------


async def _handle_pause_job(args: dict[str, Any]) -> list[types.TextContent]:
    task_id = args["task_id"]
    result = _cloud_post(f"/api/jobs/{task_id}/pause", {})
    if result is None:
        return _error_text(
            "sage-solver-cloud is not reachable. Check that the server is running."
        )
    # 4xx/5xx: result has 'detail' or 'error'
    if "detail" in result or "error" in result:
        detail = result.get("detail") or result.get("error", "unknown error")
        # Friendly message for common case: job already finished
        if isinstance(detail, dict):
            detail = detail.get("detail", str(detail))
        if "only running" in str(detail).lower() or "cannot pause" in str(detail).lower():
            return _error_text(
                f"Job {task_id} cannot be paused — it is not currently running.\n"
                "Use get_job_progress to check the current status."
            )
        return _error_text(f"Cannot pause job {task_id}: {detail}")
    return _success_text(
        "pause_job",
        f"✓ Pause requested for job {task_id}.\n"
        "The solver will stop at the next checkpoint and save the current best solution.\n"
        "Use get_job_progress to confirm the job transitions to 'paused' status.",
    )


async def _handle_resume_job(args: dict[str, Any]) -> list[types.TextContent]:
    task_id = args["task_id"]
    # Get current job state for gap info
    job = _cloud_get(f"/api/jobs/{task_id}")
    result = _cloud_post(f"/api/jobs/{task_id}/resume", {})
    if result is None:
        return _error_text(
            "sage-solver-cloud is not reachable. Check that the server is running."
        )
    if "detail" in result or "error" in result:
        detail = result.get("detail") or result.get("error", "unknown error")
        if isinstance(detail, dict):
            detail = detail.get("detail", str(detail))
        if "only paused" in str(detail).lower() or "cannot resume" in str(detail).lower():
            status = job.get("status", "unknown") if job else "unknown"
            return _error_text(
                f"Job {task_id} cannot be resumed — current status is '{status}'.\n"
                "Only paused jobs can be resumed."
            )
        return _error_text(f"Cannot resume job {task_id}: {detail}")
    gap_info = ""
    if isinstance(job, dict) and job.get("gap_pct") is not None:
        gap_info = f" (gap was {job['gap_pct']:.1f}%)"
    return _success_text(
        "resume_job",
        f"✓ Job {task_id} resumed{gap_info}.\n"
        "The solver will warm-start from the saved incumbent solution.\n"
        "Use get_job_progress to monitor convergence.",
    )


async def _handle_get_job_progress(args: dict[str, Any]) -> list[types.TextContent]:
    task_id = args["task_id"]
    progress = _cloud_get(f"/api/jobs/{task_id}/progress")
    if progress is None:
        return _error_text("sage-solver-cloud is not running or job not found.")
    # Narrate progress in plain language
    lines = [f"Job {task_id} status: {progress.get('status', 'unknown')}"]
    elapsed = progress.get("elapsed_seconds", 0)
    h, remainder = divmod(int(elapsed), 3600)
    m = remainder // 60
    lines.append(f"Elapsed: {h}h {m}m" if h else f"Elapsed: {m}m")
    if progress.get("gap_pct") is not None:
        lines.append(f"Current gap: {progress['gap_pct']:.1f}%")
    if progress.get("best_incumbent") is not None:
        lines.append(f"Best solution found: objective = {progress['best_incumbent']:.4f}")
    if progress.get("best_bound") is not None:
        lines.append(f"Best bound: {progress['best_bound']:.4f}")
    if progress.get("stall_detected"):
        lines.append("Warning: solver progress appears stalled.")
    return _success_text("get_job_progress", "\n".join(lines))


async def _handle_check_notifications(args: dict[str, Any]) -> list[types.TextContent]:
    # Read notifications blob
    notif_blob = _cloud_get("/blobs/notifications/pending")
    if notif_blob is None or not notif_blob:
        return _success_text("check_notifications", "No pending notifications.")
    try:
        data = json.loads(notif_blob) if isinstance(notif_blob, str) else notif_blob
    except Exception:
        return _success_text("check_notifications", "No pending notifications.")
    pending = data.get("pending", [])
    if not pending:
        return _success_text("check_notifications", "No pending notifications.")
    lines = [f"{len(pending)} job(s) completed since last check:"]
    for n in pending:
        lines.append(f"  {n['task_id']}: {n['problem_name']} \u2014 {n['status']}")
    # Clear notifications
    _cloud_post(
        "/api/tools/write_blob",
        {
            "key": "notifications/pending",
            "data": json.dumps({"schema_version": "2.0", "pending": []}),
            "content_type": "application/json",
        },
    )
    return _success_text("check_notifications", "\n".join(lines))


# ---------------------------------------------------------------------------
# Register tool handlers (must come after all handler definitions)
# ---------------------------------------------------------------------------

_TOOL_HANDLERS.update({
    "solve_optimization": _handle_solve_optimization,
    "read_data_file": _handle_read_data_file,
    "solve_from_file": _handle_solve_from_file,
    "explain_solution": _handle_explain_solution,
    "check_feasibility": _handle_check_feasibility,
    "generate_template": _handle_generate_template,
    "suggest_relaxations": _handle_suggest_relaxations,
    "sage_status": _handle_sage_status,
    "pause_job": _handle_pause_job,
    "resume_job": _handle_resume_job,
    "get_job_progress": _handle_get_job_progress,
    "check_notifications": _handle_check_notifications,
})


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


async def _run_server() -> None:
    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            server.create_initialization_options(),
        )


def main() -> None:
    """Start the SAGE MCP server using stdio transport.

    Discovers a running sage-solver-cloud via ~/.sage/cloud.json.
    Falls back to starting cloud as a subprocess if discovery fails.
    """
    import asyncio

    import sys

    logging.basicConfig(level=logging.WARNING, stream=sys.stderr)

    def _log(msg: str) -> None:
        """Write to stderr with immediate flush — required for MCP log visibility."""
        sys.stderr.write(msg + "\n")
        sys.stderr.flush()

    _log("[SAGE] sage-solver-mcp starting...")

    # Try discovery-based cloud detection first
    try:
        from sage_solver_mcp.cloud import find_cloud

        _log("[SAGE] Checking for running sage-solver-cloud...")
        cloud = find_cloud()
        if cloud is not None:
            _state.cloud_url = cloud.url
            _state.cloud_api_key = cloud.api_key
            _log(f"[SAGE] sage-solver-cloud discovered at {cloud.url} (v{cloud.version})")
            _log(f"[SAGE] Dashboard: {cloud.url}/")
        else:
            _log("[SAGE] No running sage-solver-cloud found via discovery.")
            # Fallback: start cloud as a subprocess
            try:
                from sage_solver_mcp.cloud_process import get_cloud

                _log("[SAGE] Launching sage-solver-cloud subprocess...")
                cloud_proc = get_cloud()
                _state.cloud_url = cloud_proc.base_url
                _state.cloud_api_key = cloud_proc.api_key

                _log(f"[SAGE] sage-solver-cloud started at {cloud_proc.base_url}")
                _log(f"[SAGE] Dashboard: {cloud_proc.base_url}/")
                _log(f"[SAGE] API key: {cloud_proc.api_key[:16]}...")
            except Exception as exc:
                _log(f"[SAGE] sage-solver-cloud not available: {exc}")
    except Exception as exc:
        _log(f"[SAGE] sage-solver-cloud discovery failed: {exc}")

    _log("[SAGE] MCP server ready.")
    asyncio.run(_run_server())
